source "https://rubygems.org"

gem "jekyll"
gem "kramdown"
gem "rake"
gem "bourbon"
gem "neat"
gem "jekyll-assets"
gem "execjs"
gem "uglifier"
gem "sass"
gem "coffee-script"
gem "jekyll-archives"
gem "jekyll-sitemap"
gem "rouge"
