source 'https://rubygems.org'
ruby '2.3.1'

gem 'jekyll'
gem 'kramdown'
gem 'rake'
gem 'bourbon'
gem 'neat'
gem 'jekyll-assets'
gem 'execjs'
gem 'yui-compressor'
gem 'sass'
gem 'coffee-script'
gem 'jekyll-archives'
gem 'jekyll-sitemap'
gem 'rouge'
gem 'jekyll-redirect-from'
gem 'octopress-paginate'

# Deployment
gem 'rack-jekyll'
gem 'puma'
gem 'typekit-client'
gem 'letsencrypt_rack'
